config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'

  get 'sessions/create'

  get 'sessions/destroy'

  resources :users

  get "/log-in" => "sessions#new"

  post "/log-in" => "sessions#create"

  delete "/log-out" => "sessions#destroy", as: :log_out

  root 'home#index'

end

app/models/user.rb
class User < ActiveRecord::Base

	attr_accessor :password

	validates_confirmation_of :password

  before_save :encrypt_password


  has_attached_file :avatar, :styles => 
  { :medium => "300x300", :thumb => "100x100" }, 
  :default_url => "/images/:style/missing.png" 
  validates_attachment_content_type :avatar, 
  :content_type => /\Aimage\/.*\Z/



	def encrypt_password
	self.password_salt = BCrypt::Engine.generate_salt

  self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
	end

  def self.authenticate(email,password)
  	
  	user = User.where(email: email).first

  if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)

  user

  else

  nil

  end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	
  def current_user

  @current_user ||= User.find(session[:user_id]) if session[:user_id]

  end

  helper_method :current_user

  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	
  def new
  end

  def create
  	#try to authenticate the user - if they authenticate successfully, an instance of the User model is returned

  @user = User.authenticate(params[:email], params[:password])

    #if an instance is returned and @user is not nil...

    if @user

     #let the user know they've been logged in with a flash message

    flash[:notice] = "You've been logged in."

      #THIS IS THE MOST IMPORTANT PART. Actually log the user in by storing their ID in the session hash with the [:user_id] key!

    session[:user_id] = @user.id

     #then redirect them to the homepage

    redirect_to "/"

    else

      #whoops, either the user wasn't in the database or their password is incorrect, so let them know, then redirect them back to the log in page

    flash[:alert] = "There was a problem logging you in."

    redirect_to log_in_path

    end
  end

  def destroy

  session[:user_id] = nil

  flash[:notice] = "You've been logged out successfully."

  redirect_to "/"

  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "Welcome to the site!"
      redirect_to "/"
    else
      flash[:alert] = "There was a problem creating account>Please try again."
      redirect_to :back
    end
  end

  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    flash[:notice] = "User has been updated"
    redirect_to user_path
  end

  def destroy
    User.find(params[:id]).destroy
      redirect_to users_path
  end

  private

  def user_params
  params.require(:user).permit(:email, :password, :password_confirmation, :username, :avatar)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<h1>WELCOME</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsPaperclip</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= flash[:notice] if flash[:notice] %> 
	<%= flash[:alert] if flash[:alert] %>

  <nav>
		<ul>
			<li><%= link_to "Home", root_path %></li>
			<li><%= link_to "Users", users_path %></li>
			 	<% if !current_user %>
			<li><%= link_to "Login", log_in_path %></li>
			<li><%= link_to "Sign up", new_user_path %></li>
			<% else %>
			<li><%= link_to "Logout", log_out_path, method: :delete %></li>
			<% end %>
		</ul>
	</nav>

<%= yield %>

</body>
</html>

app/views/users/edit.html.erb
<h2>Edit Profile</h2>

<%=form_for @user, html: { multipart: true } do |f| %>

<%=f.label :email %>

<%=f.text_field :email %>

<%=f.label :password %>

<%=f.password_field :password %>

<%=f.label :password_confirmation %>

<%=f.password_field :password_confirmation %>

<%=f.label :username %>

<%=f.text_field :username %>

<%= f.label :avatar %>
<%= f.file_field :avatar %>

<%=f.submit "Update" %>

<%end%>

app/views/users/index.html.erb
<h1>All USERS</h1>
<hr>
<br>
<% @users.each do |user| %>
  <tr>
    <td><%= image_tag user.avatar.url(:small) %></td>
    <td><%= link_to user.username, user_path(user.id) %></td>
  </tr>
<br>
<hr>
<% end %>
<br>
<%= link_to "Go Home", "/" %>

app/views/users/new.html.erb
<h2>Sign Up</h2>

<%=form_for User.new, html: { multipart: true } do |f| %>

<%=f.label :email %>

<%=f.text_field :email %>

<%=f.label :password %>

<%=f.password_field :password %>

<%=f.label :password_confirmation %>

<%=f.password_field :password_confirmation %>

<%=f.label :username %>

<%=f.text_field :username %>

<%= f.label :avatar %>
<%= f.file_field :avatar %>

<%=f.submit "Sign Up" %>

<%end%>

app/views/users/show.html.erb
<div id="user">
<h2>Welcome <%= @user.username %></h2>
<p><%= image_tag @user.avatar.url(:small) %></p>
<p><%= @user.email %></p>
<p><%= @user.username %></p>
</div>

<div id ="cd">
<h3><%= link_to("Delete Profile", user_path(@user), method: :delete) %></h3>
<h3><%= link_to "Edit Profile", edit_user_path(@user) %></h3>
<%= link_to "Go Home", "/" %>
<br>
</div>